version: '3.8'


services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://host.docker.internal:3000/api}
        VITE_RECOMMENDATION_API_URL: ${VITE_RECOMMENDATION_API_URL:-http://host.docker.internal:8000/api}
        VITE_APP_NAME: ${VITE_APP_NAME:-NutriSuggest}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
    container_name: nutrisuggest-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - nutrisuggest-frontend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      NGINX_HOST: ${NGINX_HOST:-localhost}
      NGINX_PORT: ${NGINX_PORT:-80}

networks:
  nutrisuggest-frontend-network:
    driver: bridge
    name: nutrisuggest-frontend-network